import type {OpportunityCandidate,OpportunityDirection,OpportunityStatus,SqueezeOpportunityResult} from "./types";
const clamp=(v:number,min=0,max=100)=>Math.min(max,Math.max(min,v)); const round=(v:number,d=2)=>Number(v.toFixed(d));
type Phase="WATCH"|"BUILDING"|"IMMINENT"|"ACTIVE"|"EXHAUSTION";
export interface OpportunitySideInput{direction:OpportunityDirection;sourceSqueeze:"short_squeeze"|"long_squeeze";currentPrice:number;squeezeProbability:number;squeezePhase:Phase;alertScore:number;triggerPressure:number;liquidationConfirmation:number;dataReliability:number;zone:{priceLow:number;priceHigh:number;centerPrice:number;intensity:number;confidence:number}|null;candidateTargetZones:number[];strongestZoneCenter:number|null;takerBuyRatio:number|null;takerCoveragePercent:number;oiChange5mPercent:number|null;priceChange5mPercent:number|null;decisionDirection:"bullish"|"bearish"|"neutral"|null;decisionStrength:number|null;tradingPermission:string|null;}
function phasePoints(p:Phase){switch(p){case"ACTIVE":return 30;case"IMMINENT":return 24;case"BUILDING":return 14;case"EXHAUSTION":return 4;default:return 0}}
function statusFrom(score:number,phase:Phase,blockers:string[]):OpportunityStatus{if(phase==="EXHAUSTION")return"COOLDOWN";if(blockers.length)return"WATCH";if(phase==="ACTIVE"&&score>=72)return"TRIGGERED";if((phase==="IMMINENT"||phase==="ACTIVE")&&score>=58)return"SETUP";if(phase==="BUILDING"&&score>=48)return"SETUP";return"WATCH";}
export function evaluateSqueezeOpportunitySide(i:OpportunitySideInput):OpportunityCandidate{const blockers:string[]=[],confirmations:string[]=[],reasons:string[]=[];if(!Number.isFinite(i.currentPrice)||i.currentPrice<=0)blockers.push("현재가가 유효하지 않습니다.");if(i.dataReliability<45)blockers.push(`데이터 신뢰도 부족 ${round(i.dataReliability,1)}/100`);if(i.takerCoveragePercent<60)blockers.push(`Taker coverage 부족 ${round(i.takerCoveragePercent,0)}%`);if(i.tradingPermission==="blocked")blockers.push("Decision V2 trading permission blocked");const isLong=i.direction==="long";const td=i.takerBuyRatio==null?0:isLong?(i.takerBuyRatio-.5)*200:(.5-i.takerBuyRatio)*200;const takerConfirmation=clamp(50+td);let oiConfirmation=45;if(i.oiChange5mPercent!=null){const oiAbs=Math.min(30,Math.abs(i.oiChange5mPercent)*20);const pd=i.priceChange5mPercent==null?0:isLong?i.priceChange5mPercent:-i.priceChange5mPercent;oiConfirmation=clamp(45+oiAbs+(pd>0?15:pd<0?-10:0));}const matches=i.decisionDirection===(isLong?"bullish":"bearish"),opposes=i.decisionDirection===(isLong?"bearish":"bullish");const decisionAlignment=matches?clamp(60+(i.decisionStrength??0)*.4):opposes?clamp(40-(i.decisionStrength??0)*.3):50;if(takerConfirmation>=58)confirmations.push(`${isLong?"매수":"매도"} Taker 압력 확인 ${round(takerConfirmation,1)}/100`);if(oiConfirmation>=58)confirmations.push(`OI/가격 동행 확인 ${round(oiConfirmation,1)}/100`);if(i.liquidationConfirmation>=45)confirmations.push(`실제 청산 확인 ${round(i.liquidationConfirmation,1)}/100`);if(decisionAlignment>=58)confirmations.push(`Decision V2 방향 정렬 ${round(decisionAlignment,1)}/100`);const zoneScore=i.zone?clamp(i.zone.intensity*.55+i.zone.confidence*.45):0;if(!i.zone)blockers.push("유효한 예상 청산 구간이 없습니다.");const score=clamp(i.squeezeProbability*.25+phasePoints(i.squeezePhase)+i.alertScore*.12+zoneScore*.12+takerConfirmation*.12+oiConfirmation*.08+i.liquidationConfirmation*.06+decisionAlignment*.05);const confidence=clamp(i.dataReliability*.35+Math.min(100,i.takerCoveragePercent)*.15+(i.zone?.confidence??0)*.2+i.alertScore*.15+Math.min(100,confirmations.length*20)*.15);const triggerPrice=i.zone?.centerPrice??null;const distanceToTriggerPercent=triggerPrice?round((triggerPrice-i.currentPrice)/i.currentPrice*100,4):null;const candidateZones=(i.candidateTargetZones??[])
    .filter(x=>Number.isFinite(x)&&x>0)
    .filter(x=>triggerPrice==null?false:(isLong?x>triggerPrice:x<triggerPrice))
    .filter(x=>Math.abs((x-i.currentPrice)/i.currentPrice*100)<=4.5)
    .sort((a,b)=>isLong?a-b:b-a);

  const deduped:number[]=[];
  for(const x of candidateZones){
    if(!deduped.some(y=>Math.abs(x-y)/i.currentPrice*100<0.12))deduped.push(x);
  }

  const fallback1=triggerPrice!=null?round(triggerPrice*(isLong?1.004:.996),2):null;
  const fallback2=triggerPrice!=null?round(triggerPrice*(isLong?1.008:.992),2):null;
  const fallback3=triggerPrice!=null?round(triggerPrice*(isLong?1.012:.988),2):null;

  const targetPrice1=deduped[0]??fallback1;
  const targetPrice2=deduped[1]??fallback2;
  let extendedTargetPrice:number|null=deduped[2]??null;

  if(extendedTargetPrice==null && i.strongestZoneCenter!=null && triggerPrice!=null){
    const strongestDistance=Math.abs((i.strongestZoneCenter-i.currentPrice)/i.currentPrice*100);
    const validDirection=isLong?i.strongestZoneCenter>triggerPrice:i.strongestZoneCenter<triggerPrice;
    if(validDirection && strongestDistance<=4.5)extendedTargetPrice=i.strongestZoneCenter;
  }
  if(extendedTargetPrice==null)extendedTargetPrice=fallback3;

  const targetPrice=targetPrice1;
  const target1DistancePercent=targetPrice1!=null?round((targetPrice1-i.currentPrice)/i.currentPrice*100,4):null;
  const target2DistancePercent=targetPrice2!=null?round((targetPrice2-i.currentPrice)/i.currentPrice*100,4):null;
  const extendedTargetDistancePercent=extendedTargetPrice!=null?round((extendedTargetPrice-i.currentPrice)/i.currentPrice*100,4):null;

  let invalidationPrice:number|null=null;if(i.zone){const span=Math.max(i.zone.priceHigh-i.zone.priceLow,i.currentPrice*.0025);invalidationPrice=isLong?round(i.zone.priceLow-span*.6,2):round(i.zone.priceHigh+span*.6,2);}reasons.push(i.squeezePhase==="ACTIVE"?`${i.sourceSqueeze} ACTIVE — 반대 방향 모멘텀 기회 감시`:`${i.sourceSqueeze} ${i.squeezePhase} — 기회 점수 ${round(score,1)}/100`);reasons.push(`Squeeze probability ${round(i.squeezeProbability,1)} · Alert ${round(i.alertScore,1)} · Zone ${round(zoneScore,1)}`);reasons.push(`Taker ${round(takerConfirmation,1)} · OI ${round(oiConfirmation,1)} · Liquidation ${round(i.liquidationConfirmation,1)} · Decision ${round(decisionAlignment,1)}`);reasons.push(`Target ladder ${targetPrice1??"—"} → ${targetPrice2??"—"} → ${extendedTargetPrice??"—"}`);return{direction:i.direction,sourceSqueeze:i.sourceSqueeze,status:statusFrom(score,i.squeezePhase,blockers),score:round(score),confidence:round(confidence),triggerPrice,triggerZoneLow:i.zone?.priceLow??null,triggerZoneHigh:i.zone?.priceHigh??null,targetPrice,targetPrice1,targetPrice2,extendedTargetPrice,invalidationPrice,distanceToTriggerPercent,target1DistancePercent,target2DistancePercent,extendedTargetDistancePercent,squeezeProbability:round(i.squeezeProbability),squeezePhase:i.squeezePhase,takerConfirmation:round(takerConfirmation),oiConfirmation:round(oiConfirmation),liquidationConfirmation:round(i.liquidationConfirmation),decisionAlignment:round(decisionAlignment),dataReliability:round(i.dataReliability),blockers,confirmations,reasons};}
export function buildSqueezeOpportunityResult(input:{currentPrice:number;longOpportunity:OpportunitySideInput;shortOpportunity:OpportunitySideInput;}):SqueezeOpportunityResult{const longOpportunity=evaluateSqueezeOpportunitySide(input.longOpportunity),shortOpportunity=evaluateSqueezeOpportunitySide(input.shortOpportunity);const eligible=(x:OpportunityCandidate)=>!x.blockers.length&&["SETUP","TRIGGERED"].includes(x.status);let preferredDirection:SqueezeOpportunityResult["preferredDirection"]="none";if(eligible(longOpportunity)&&eligible(shortOpportunity))preferredDirection=Math.abs(longOpportunity.score-shortOpportunity.score)<8?"balanced":longOpportunity.score>shortOpportunity.score?"long":"short";else if(eligible(longOpportunity))preferredDirection="long";else if(eligible(shortOpportunity))preferredDirection="short";else if(!longOpportunity.blockers.length||!shortOpportunity.blockers.length)preferredDirection="balanced";const any= [longOpportunity.status,shortOpportunity.status].some(x=>x==="SETUP"||x==="TRIGGERED");return{symbol:"BTCUSDT",calculatedAt:new Date().toISOString(),currentPrice:input.currentPrice,longOpportunity,shortOpportunity,preferredDirection,permission:any?"paper_candidate":longOpportunity.blockers.length&&shortOpportunity.blockers.length?"blocked":"observe",strategyVersion:"squeeze-opportunity-v7.19.1"};}
