import type {PositionCluster,PositionClusterMap} from "./types";
const clamp=(v:number,min=0,max=100)=>Math.min(max,Math.max(min,v));
const round=(v:number,d=4)=>{const m=10**d;return Math.round(v*m)/m};
export interface ExchangeSnapshotInput{exchange:string;fetchedAt:string;lastPrice:number;openInterestUsd:number;takerBuyRatio:number|null;}
export function buildPositionClusterMap(input:{snapshots:ExchangeSnapshotInput[];currentPrice:number;now?:Date;lookbackHours?:number;halfLifeHours?:number;binSizePercent?:number;}):PositionClusterMap{
 const now=input.now??new Date(),lookback=input.lookbackHours??6,half=input.halfLifeHours??3,binPct=input.binSizePercent??.25;
 if(!Number.isFinite(input.currentPrice)||input.currentPrice<=0)throw new Error("currentPrice must be > 0");
 const bin=Math.max(50,Math.round((input.currentPrice*binPct/100)/50)*50),cutoff=now.getTime()-lookback*3600000;
 const groups=new Map<string,ExchangeSnapshotInput[]>();
 for(const r of input.snapshots){const t=new Date(r.fetchedAt).getTime();if(!Number.isFinite(t)||t<cutoff||t>now.getTime()+60000)continue;(groups.get(r.exchange)??(groups.set(r.exchange,[]),groups.get(r.exchange)!)).push(r)}
 type B={low:number;high:number;center:number;longUsd:number;shortUsd:number;longW:number;shortW:number;ex:Set<string>;samples:number;confNum:number;confDen:number};
 const bins=new Map<number,B>();
 for(const rows of groups.values()){rows.sort((a,b)=>+new Date(a.fetchedAt)-+new Date(b.fetchedAt));for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i];if(a.openInterestUsd<=0||b.openInterestUsd<=0||a.lastPrice<=0||b.lastPrice<=0)continue;const oi=b.openInterestUsd-a.openInterestUsd;if(oi<=0)continue;const pc=(b.lastPrice-a.lastPrice)/a.lastPrice*100;let side:"long"|"short"|"neutral"="neutral";if(pc>=.03)side="long";else if(pc<=-.03)side="short";if(side==="neutral")continue;let conf=clamp(25+Math.abs(pc)*180,25,75);if(b.takerBuyRatio!=null){const bias=(b.takerBuyRatio-.5)*2,support=(side==="long"&&bias>0)||(side==="short"&&bias<0);if(support)conf=clamp(conf+15,0,90);else if(Math.abs(bias)>=.08)conf=clamp(conf-15,10,90)}const age=Math.max(0,(now.getTime()-+new Date(b.fetchedAt))/3600000),rec=Math.pow(.5,age/half),w=oi*(conf/100)*rec,price=(a.lastPrice+b.lastPrice)/2,idx=Math.floor(price/bin),low=idx*bin,high=low+bin,center=low+bin/2;const x=bins.get(idx)??{low,high,center,longUsd:0,shortUsd:0,longW:0,shortW:0,ex:new Set<string>(),samples:0,confNum:0,confDen:0};if(side==="long"){x.longUsd+=oi;x.longW+=w}else{x.shortUsd+=oi;x.shortW+=w}x.ex.add(b.exchange);x.samples++;x.confNum+=conf*w;x.confDen+=w;bins.set(idx,x)}}
 const all=[...bins.values()],maxL=Math.max(0,...all.map(x=>x.longW)),maxS=Math.max(0,...all.map(x=>x.shortW));
 const clusters:PositionCluster[]=all.map(x=>{const li=maxL?clamp(x.longW/maxL*100):0,si=maxS?clamp(x.shortW/maxS*100):0;const dom:"long"|"short"|"balanced"=Math.abs(li-si)<10?"balanced":li>si?"long":"short";const base=x.confDen?x.confNum/x.confDen:0;return{priceLow:round(x.low,2),priceHigh:round(x.high,2),centerPrice:round(x.center,2),distanceFromCurrentPercent:round((x.center-input.currentPrice)/input.currentPrice*100,4),longIntensity:round(li,2),shortIntensity:round(si,2),dominantSide:dom,confidence:round(clamp(base+Math.min(21,(x.ex.size-1)*7)+Math.min(10,(x.samples-1)*2),0,95),2),estimatedNewLongOiUsd:round(x.longUsd,2),estimatedNewShortOiUsd:round(x.shortUsd,2),exchangeCount:x.ex.size,contributingExchanges:[...x.ex].sort(),sampleCount:x.samples}}).sort((a,b)=>a.centerPrice-b.centerPrice);
 const strongestLongCluster=clusters.filter(x=>x.longIntensity>0).sort((a,b)=>b.longIntensity-a.longIntensity)[0]??null,strongestShortCluster=clusters.filter(x=>x.shortIntensity>0).sort((a,b)=>b.shortIntensity-a.shortIntensity)[0]??null;
 return{symbol:"BTCUSDT",calculatedAt:now.toISOString(),lookbackHours:lookback,halfLifeHours:half,currentPrice:round(input.currentPrice,2),binSizeUsd:bin,totalEstimatedNewLongOiUsd:round(clusters.reduce((s,x)=>s+x.estimatedNewLongOiUsd,0),2),totalEstimatedNewShortOiUsd:round(clusters.reduce((s,x)=>s+x.estimatedNewShortOiUsd,0),2),clusters,strongestLongCluster,strongestShortCluster,sourceExchangeCount:groups.size,sourceSnapshotCount:input.snapshots.length,strategyVersion:"position-cluster-map-v7.12"};
}
