begin;

create table if not exists public.performance_battle_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null default 'BTCUSDT',
  calculated_at timestamptz not null default now(),
  linked_pairs integer not null default 0,
  candidate_v2_snapshots integer not null default 0,
  excluded_lagged_pairs integer not null default 0,
  verdict text not null,
  verdict_reason text not null,
  overall_metrics jsonb not null default '[]'::jsonb,
  regime_metrics jsonb not null default '[]'::jsonb,
  v2_diagnostics jsonb not null default '{}'::jsonb,
  methodology jsonb not null default '[]'::jsonb,
  strategy_version text not null,
  created_at timestamptz not null default now(),
  constraint performance_battle_verdict_check
    check (verdict in ('v1_leads','v2_leads','mixed','inconclusive'))
);

create index if not exists idx_performance_battle_symbol_time
  on public.performance_battle_snapshots(symbol, calculated_at desc);

comment on table public.performance_battle_snapshots is
  'Phase 7-4: 같은 시점 V1/V2 판단을 기존 forward backtest 결과로 공정 비교한 요약 snapshot';

alter table public.performance_battle_snapshots enable row level security;

commit;
