begin;

create table if not exists public.signal_calibration_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null default 'BTCUSDT',
  calculated_at timestamptz not null default now(),
  window_hours integer not null default 168 check (window_hours > 0),
  mode text not null default 'observation_only' check (mode in ('observation_only')),
  news_candidate jsonb not null default '{}'::jsonb,
  funding_candidate jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  strategy_version text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_signal_calibration_symbol_time
  on public.signal_calibration_snapshots(symbol, calculated_at desc);

comment on table public.signal_calibration_snapshots is
  'Phase 7-3A.3 observation-only News dynamic threshold / Funding crowding calibration snapshots';

alter table public.signal_calibration_snapshots enable row level security;

commit;
