begin;
create table if not exists public.shadow_signal_validation_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null default 'BTCUSDT',
  calculated_at timestamptz not null default now(),
  window_hours integer not null default 168 check(window_hours>0),
  calibration_ratio numeric(5,4) not null default 0.7 check(calibration_ratio>0 and calibration_ratio<1),
  return_threshold_percent numeric(12,6) not null default 0.1,
  news_validation jsonb not null default '{}'::jsonb,
  funding_validation jsonb not null default '{}'::jsonb,
  overall_verdict text not null,
  recommendations jsonb not null default '[]'::jsonb,
  strategy_version text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_shadow_signal_validation_symbol_time on public.shadow_signal_validation_snapshots(symbol,calculated_at desc);
comment on table public.shadow_signal_validation_snapshots is 'Phase 7-3A.4 look-ahead 방지 70/30 shadow signal validation snapshots';
alter table public.shadow_signal_validation_snapshots enable row level security;
commit;
